<?php
use think\Route;
/* Route::rule('new','home/Index/index'); */
Route::rule([
			'AQuestion'=>'Admin/Question/save_question',
			'AQuestionD'=>'Admin/Question/del_question',
			'AOption'=>'Admin/Question/save_option',
			'AOptionD'=>'Admin/Question/del_option',
			'AQuestionL'=>'Admin/Question/question_list',
			'ADrawP'=>'admin/Draw/draw_pass',
			'ADrawL'=>'admin/Draw/draw_list',
			'AOrderL'=>'admin/Order/order_list',
			'AStoryD'=>'admin/Story/del_story',
			'BrowseT'=>'admin/Statistics/browse',
			'ActivityT'=>'admin/Statistics/activity',
			'KindT'=>'admin/Statistics/statistics_kind',
			'RoleT'=>'admin/Statistics/user_role_kind',
			'UserT'=>'admin/Statistics/user',
			'StoryT'=>'admin/Statistics/story',
			'DisputeL'=>'admin/Dispute/dispute_list',
			'CheckPlanner'=>'admin/User/check_planner',
			'UserChcekList'=>'admin/User/user_check_list',
			



]);



Route::rule([
			'EmailLogin'=>'home/User/email_login',
			'BindEmail'=>'home/User/bind_email_link',
			'email'=>'home/Sendmail/email',
			'CheckEmail'=>'home/User/check_email',
			'orderadd'=>'home/Order/add',
			'balance'=>'home/Vip/check_balance',
			'running'=>'home/Vip/running',
			'Draw'=>'home/Draw/draw_submit', 
			'banks'=>'home/User/bank_save',
			'bankd'=>'home/User/bank_del',
			'bankl'=>'home/User/bank_list',
			'actls'=>'home/Activity/similar',
			'ActivityC'=>'home/Activity/activity_cancel',
			'SlotC'=>'home/Activity/slot_cancel',
			'storys'=>'home/Story/similar',
			'orderl'=>'home/Vip/order_list',
			'storyp'=>'home/Story/praise',
			'trades'=>'home/Trade/soon',
			'vipact'=>'home/Vip/activ_list',
			'storyc'=>'home/Story/create_list',
			'attentionl'=>'home/Comment/my_att_list',
			'collectional'=>'home/Comment/col_act_list',
			'sysmsgl'=>'home/Sysmsg/msg_list',
			'SysMsgD'=>'home/Sysmsg/msg_detail',
			'msgsay'=>'home/Msg/mysay',
			'msgreply'=>'home/Msg/my_replay',
			'ActivOrderNum'=>'home/Order/get_slot_num',
			'ActivOrderHouseNum'=>'home/Order/get_house_num',
			'AddressL'=>'home/User/address_list',
			'MyPraise'=>'home/Comment/praise_list',
			'CommentS'=>'home/Comment/save_comment',
			'Calculate'=>'home/Order/calculate_price',
			'GroupD'=>'home/Comment/del_collegroup',
			'AttentionOL'=>'home/Comment/att_other_list',
			'OrderD'=>'home/Order/detail',
			'OrderIsPay'=>'home/Order/pay_status',
			'LeaveL'=>'home/Comment/leave_list',
			'test'=>'home/Vip/test',
			'Browse'=>'home/Browse/index',
			'UserC'=>'home/User/user_cancel',
			'ReportU'=>'home/Comment/save_report',
			'DisputeS'=>'home/Comment/save_dispute',
			'PopularCity'=>'home/Activity/popular_list',
			'PopularAct'=>'home/Activity/popular_act_list',
			'PaywordSet'=>'home/User/set_pay_password',
			'PaywordEdit'=>'home/User/edit_pay_pwd',
			'PaywordEditCode'=>'home/User/find_pay_pwd',
			'SoonAct'=>'home/Activity/soon_activity',
			'GuessAct'=>'home/Activity/guess_activity',
			'Pay'=>'home/Order/to_pay',
			'PopularCityStory'=>'home/Story/popular_list',
			'RegisterS'=>'home/Index/register_save',
			'EditMobile'=>'home/User/edit_mobile', 
			'Planner'=>'home/User/planner_list', 
			'IdentifyCard'=>'home/User/identify_card', 
			'TradCenter'=>'home/Vip/trad_list',
			'TranslateS'=>'home/Translate/translate',
			'TranslateD'=>'home/Translate/del_translate',
			'TranslateL'=>'home/Translate/translate_list',
			'TranslateDetail'=>'home/Translate/translate_detail',
			'ActivityE'=>'home/Activity/activity_edit',
			'ErollS'=>'home/Enroll/enroll',
			'ErollL'=>'home/Enroll/enroll_list',
			'ErollD'=>'home/Enroll/del_enroll',
			'ErollA'=>'home/Enroll/audit_enroll',
			'ErollListMy'=>'home/Enroll/my_enroll_list',
			'InviteS'=>'home/Invite/invite',
			'InviteD'=>'home/Invite/del_invite',
			'InviteA'=>'home/Invite/audit_invite',
			'ForwardS'=>'home/Forward/forward',
			'ForwardD'=>'home/Forward/del_forward',
			'Dynamic'=>'home/User/dynamic',
			'InviteListMy'=>'home/Invite/my_invite_list',
			'InviteL'=>'home/Invite/invite_list',
			'ChatList'=>'home/Chat/chat_list',
			'RegisterC'=>'home/Chat/register',
			'SendMsg'=>'home/Chat/sendmessage',
			'ReadMsg'=>'home/Chat/readmessage',
			'MsgList'=>'home/Chat/msg_list',
			'MsgCallBack'=>'home/Chat/msg_callback',
			'MyMsg'=>'home/Chat/my_msg_list',
			/* 'CommentHe'=>'home/Comment/comment_planner', */
			/* 'HeComment'=>'home/Comment/he_comment', */
			'TestPay'=>'home/Order/test',
			'OrderLPlanner'=>'home/Vip/order_list_planner',
			'RefundS'=>'home/Refund/save_refund',
			'CheckPolicy'=>'home/Refund/check_policy',
			'RefundAmount'=>'home/Refund/refund_amount', 
			'RefundLPlanner'=>'home/Refund/refund_list', 
			'AgreeRefund'=>'home/Refund/agree_refund', 
			'RefundLUser'=>'home/Refund/refund_list_user', 
			'RefundD'=>'home/Refund/refund_detail', 
			'PriceU'=>'home/Order/price_update', 
			'HouseS'=>'home/Activity/house_save', 
			'HouseD'=>'home/Activity/house_del', 
			'HouseUseNum'=>'home/Order/house_use_num', 
			'ActivityList'=>'home/Activity/activity_list_planner', 
			'SlotS'=>'home/Activity/slot_save', 
			'SlotD'=>'home/Activity/slot_delete', 
			'ImageD'=>'home/Image/image_delete', 
			'IdentifyCardPlanner'=>'home/User/identify_card_planner', 
			//'ToMyComment'=>'home/Comment/my_comment_list',	
			//'ReportUCancel'=>'home/Comment/cancel_report',
			'SysmsgA'=>'home/Sysmsg/sysmsg_add',
			'VolunteerB'=>'home/User/volunteer_become',
			'UploadB'=>'home/Upload/upload_base64',
			'QqLogin'=>'home/User/qq_login',
			'WechaLogin'=>'home/User/wecha_login', 
			'RegisterEmail'=>'home/User/register_email', 
			'CommentVisit'=>'home/Comment/comment_visiter', 
			'CommentPlannerS'=>'home/Comment/comment_planner_save', 
			'CommentPlanner'=>'home/Comment/comment_planner', 
			'SubKindList'=>'home/Kind/kind_sub', 
			'BindMobile'=>'home/User/bind_mobile_link', 
			]);
			

Route::rule([
			'Qqcallback'=>'task/Qqcallback/callback',
			'Wxcallback'=>'task/Wxcallback/callback',
			'EmailVerify'=>'task/Email/verify',
			'Error'=>'task/Error/index',

		]);			
			
// 设限制URL兼容模式
/* \think\Url::root('index.php?s=');

return [
    '__pattern__' => [
        'name' => '\w+',
    ],
    '[hello]'     => [
        ':id'   => ['index/hello', ['method' => 'get'], ['id' => '\d+']],
        ':name' => ['index/hello', ['method' => 'post']],
    ],

]; */
	